"""Cross-document references between paper/main.tex and paper/supplement.tex.

The pilot studies live in a separate supplementary document, and each document
cites tables and sections of the other. The xr package would read the other
document's .aux at compile time, which fails on a submission system that
compiles one file. Instead this script copies each document's printed label
numbers into a small tracked .tex file that the other document inputs:

    paper/supplement_labels.tex   labels of supplement.tex, read by main.tex (\\supref)
    paper/main_labels.tex         labels of main.tex, read by supplement.tex (\\mainref)

Run it after compiling both documents; `make -C paper pdf` does. A label that
is missing from the file prints as a bold ?? rather than failing the build, and
--check fails if either file is stale against the current .aux files.
"""
import _root  # noqa: F401  -- chdir to the repo root; must come first
import argparse
import sys
from pathlib import Path

PAPER = Path("paper")
PAIRS = (("supplement", "supl", "supplement_labels.tex"),
         ("main", "mainl", "main_labels.tex"))


def labels(aux):
    """label -> printed number, from the first brace group of each \\newlabel."""
    out = {}
    for line in aux.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.startswith("\\newlabel{"):
            continue
        name_end = line.index("}", len("\\newlabel{"))
        name = line[len("\\newlabel{"):name_end]
        rest = line[name_end + 1:]
        if not rest.startswith("{{"):
            continue
        depth, i = 0, 1
        for i, ch in enumerate(rest[1:], start=1):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    break
        out[name] = rest[2:i]
    return out


def render(doc, prefix):
    aux = PAPER / f"{doc}.aux"
    if not aux.exists():
        raise SystemExit(f"{aux} not found: compile {doc}.tex first")
    found = labels(aux)
    lines = [f"% Generated by code/cross_labels.py from paper/{doc}.aux. Do not edit."]
    for name in sorted(found):
        if name.startswith(("sec:", "app:", "tab:", "fig:")):
            lines.append(f"\\expandafter\\def\\csname {prefix}@{name}\\endcsname{{{found[name]}}}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    stale = []
    for doc, prefix, target in PAIRS:
        content = render(doc, prefix)
        path = PAPER / target
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path))
        else:
            path.write_bytes(content.encode("utf-8"))
    if stale:
        print("stale cross-document labels: " + ", ".join(stale))
        return 1
    print("cross-document labels " + ("verified." if args.check else "written."))
    return 0


if __name__ == "__main__":
    sys.exit(main())
