#!/usr/bin/env python3
"""Render every figure body in figures/src/ to figures/*.pdf and *.png.

figures/src/ holds ONE source per figure and is the only place a figure body
lives. The manuscript includes the rendered PNG, so main.tex no longer carries
the drawing code:

    runs/ -> manifest.py --tex -> figures/src/{matrix,gradient}.tex
                                       |
          figures/src/*.tex -> make_figures.py -> figures/*.pdf + *.png
                                       |
                                       +-> \\includegraphics in main.tex

The direction matters. An earlier version extracted the bodies FROM main.tex,
which was fine until the manuscript started including images instead of drawing
them -- at that point the extractor would have been reading its own output.
Sources moved here so the arrow only ever points one way.

matrix.tex and gradient.tex are regenerated by `manifest.py --tex` from runs/
and must not be hand-edited; the other four are static drawings.

Captions and \\label stay in the manuscript, not here. A caption is numbered
relative to its document ("Figure 4:"), which is wrong the moment the image is
used anywhere else.

    python make_figures.py            # all figures
    python make_figures.py matrix     # just fig:matrix
    python make_figures.py --list
"""
import _root  # noqa: F401  -- chdir to the repo root; must come first
                            #  (relative data paths depend on it)
import glob
import os
import re
import shutil
import subprocess
import sys
import tempfile

SRC = "figures/src"
OUT = "figures"
# The manuscript includes figures/*.png by a path relative to ITSELF, so the
# upload bundle needs its own copy. Mirrored on every run rather than copied by
# hand: otherwise regenerating figures/ leaves the paper silently building
# against last week's numbers, which is the one failure mode this repo keeps
# having. Bundles that do not exist are skipped.
MIRRORS = ("usenix_paper/figures",)
DPI = 300
# figures/{matrix,gradient,roc}.pdf are now drawn by plot_figures.py for paper/main.tex.
# This script still renders their PNGs, which the USENIX bundle includes, but must not
# overwrite those PDFs with the LaTeX-picture version.
PLOTTED = {"matrix", "gradient", "roc"}

# Packages the figure bodies use. Deliberately a fixed list rather than a copy of
# the manuscript preamble: usenix.sty sets a 7in two-column geometry, which would
# fight the standalone class over the page box and silently pad every export.
PREAMBLE = r"""\usepackage[T1]{fontenc}
\usepackage{mathptmx}   % Times math, as the paper -- needs the rsfs
                        % TFMs, which mathptmx pulls in at \tiny (5pt)
\usepackage{xcolor}
\usepackage{booktabs}
\usepackage{graphicx}  % \rotatebox, used by the ROC axis label
\usepackage{pslatex}    % as usenix.sty: gives \texttt its real bold
\usepackage{pict2e}
"""


def _balanced(text, start):
    """End index just past the {...} group that starts at `start`.

    A caption contains braces -- \\texttt{...}, \\S\\ref{...} -- so a regex that
    stops at the first `}` truncates mid-command and leaves the export
    uncompilable. Counting is the only thing that works here."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{" and text[i - 1] != "\\":
            depth += 1
        elif text[i] == "}" and text[i - 1] != "\\":
            depth -= 1
            if depth == 0:
                return i + 1
    raise ValueError("unbalanced braces")


def _strip(body):
    for cmd in (r"\caption", r"\label"):
        while (i := body.find(cmd)) != -1:
            j = body.find("{", i)
            body = body[:i] + body[_balanced(body, j):]
    return body.strip()


# USENIX geometry, from usenix.sty: textwidth 7in, columnsep 0.33in.
# A figure whose content is sized in \columnwidth (the schema tabular uses
# p{0.46\columnwidth}) renders at the WRONG width unless the export reproduces
# the manuscript's column. standalone sizes the page to the content, so without
# this the schema figure came out 338pt wide against a 241pt column -- a
# faithful-looking image of a layout that never appears in the paper.
TEXTWIDTH_PT = 505.89
COLUMNWIDTH_PT = (505.89 - 23.84) / 2


def figures(path=SRC):
    """Every figure source in figures/src/, as {name: (body, width_pt)}."""
    found = {}
    for f in sorted(glob.glob(os.path.join(path, "*.tex"))):
        text = open(f, encoding="utf-8").read()
        wide = re.search(r"^%\s*width:\s*(\w+)", text, re.M)
        w = TEXTWIDTH_PT if (wide and wide.group(1) == "textwidth") else COLUMNWIDTH_PT
        found[os.path.splitext(os.path.basename(f))[0]] = (text, w)
    return found


def export(name, body_w, outdir=OUT):
    body, width = body_w
    doc = ("\\documentclass[border=2pt]{standalone}\n" + PREAMBLE
           + "\\begin{document}\n"
           f"\\setlength{{\\columnwidth}}{{{width}pt}}%\n"
           f"\\begin{{minipage}}{{{width}pt}}%\n"
           + body + "\n\\end{minipage}\n\\end{document}\n")
    # FIXED JOBNAME, never the figure's own name. Naming the scratch file
    # roc.tex made the ROC figure's own `\IfFileExists{roc.tex}` match the
    # standalone wrapper and `\input` it into itself -- a figure that compiles
    # in the manuscript and dies here, for a reason nothing in the body shows.
    with tempfile.TemporaryDirectory() as tmp:
        open(os.path.join(tmp, "_fig.tex"), "w", encoding="utf-8").write(doc)
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                            "-halt-on-error", "_fig.tex"],
                           cwd=tmp, capture_output=True, text=True)
        pdf = os.path.join(tmp, "_fig.pdf")
        if r.returncode or not os.path.exists(pdf):
            err = [l for l in r.stdout.splitlines() if l.startswith("!")]
            print(f"  FAILED {name}: {err[0] if err else 'no PDF produced'}",
                  file=sys.stderr)
            return False
        if name not in PLOTTED:
            shutil.copy(pdf, os.path.join(outdir, f"{name}.pdf"))
        # -singlefile drops the page-number suffix pdftoppm otherwise appends,
        # which would make the filenames unstable across runs.
        subprocess.run(["pdftoppm", "-png", "-r", str(DPI), "-singlefile", pdf,
                        os.path.join(outdir, name)], check=True)
    for d in MIRRORS:
        if os.path.isdir(d):
            shutil.copy(os.path.join(outdir, f"{name}.png"),
                        os.path.join(d, f"{name}.png"))
    return True


def selfcheck():
    """Brace counting is the only non-obvious logic here, so it is the only
    thing worth a check: a caption holding nested groups must come out whole."""
    body = r"pre \caption{a {b} \texttt{c\_d} e} \label{fig:x} post"
    out = _strip(body)
    # The whole caption goes and no fragment survives: a first-brace match would
    # leave `\texttt{c\_d} e}` behind, which compiles nowhere.
    assert out.split() == ["pre", "post"], out
    got = figures()
    assert {"threat", "matrix", "gradient", "roc"} <= set(got), set(got)
    assert got["pipeline"][1] > got["matrix"][1], "figure* must render full-width"
    print(f"selfcheck OK ({len(got)} figure sources in {SRC}/)")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    if "--selfcheck" in sys.argv:
        return selfcheck()
    figs = figures()
    if "--list" in sys.argv:
        for n in figs:
            print(f"  fig:{n}")
        return
    if not figs:
        sys.exit(f"no \\label{{fig:...}} floats found in {SRC}")
    os.makedirs(OUT, exist_ok=True)
    want = args or list(figs)
    ok = 0
    for n in want:
        if n not in figs:
            print(f"  no such figure: {n}", file=sys.stderr)
            continue
        if export(n, figs[n]):
            ok += 1
            print(f"  {n:10s} -> {OUT}/{n}.pdf, {OUT}/{n}.png")
    print(f"\n{ok}/{len(want)} figures exported to {OUT}/")
    sys.exit(0 if ok == len(want) else 1)


if __name__ == "__main__":
    main()
